apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydp
  namespace: prod
  annotations:
    kubernetes.io/change-cause: 'this is my first version'
  labels: 
    app: game
spec: 
  minReadySeconds: 5
  replicas: 4
  selector: 
    matchLabels:
      app: myblueapp
  strategy:
    type: {{ .Values.strategy.dptype}}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:  
      labels:
        app: myblueapp
    spec:
      containers:
        - name: {{ .Values.containername}}
          image: {{ .Values.myimage }}
          ports:
            - containerPort: 80
          
          
            
            
